### ISSUE TITLE
Linking errors with _MCF things post v1.10

### ISSUE THREAD

**Issue by LPardue** [bwoodsend/setup-winlibs-action#3]
Thanks for this action, we use it on our project quiche. FYI something seems to have broken lately in https://github.com/brechtsanders/winlibs_mingw/issues/147. We're working around that for now by pinning at v1.10, which doesn't show the problem.

**Comment by bwoodsend** [comment]
Thanks for the heads up.

I don't want to be deciding which versions people should or shouldn't use so I'd rather not do a revert. I guess one possible policy would be to update the default winlibs tag a week or so after the corresponding winlibs release and update only if there are no regressions reported on winlibs's issue tracker rather than immediately (or as close to as I can get).

That said, is [this](https://github.com/brechtsanders/winlibs_mingw/issues/147#issuecomment-1531050347) really is all it takes to reproduce the error? If it is, I think I'll revert anyway. Edit: I forgot the part about requiring `-static`. That makes me a lot less interested in a revert.

> We're working around that for now by pinning at v1.10, which doesn't show the problem.

You can just pin the previous WinLibs tag instead (i.e. `tag: 12.2.0-16.0.0-10.0.0-msvcrt-r5`) although in this case it doesn't make any difference since all setup-winlibs-action@v1.11 changed was that default WinLibs tag.

**Comment by LPardue** [comment]
> I don't want to be deciding which versions people should or shouldn't use so I'd rather not do a revert. I guess one possible policy would be to update the default winlibs tag a week or so after the corresponding winlibs release and update only if there are no regressions reported on winlibs's issue tracker rather than immediately (or as close to as I can get).

This is totally up to you. We have a way to workaround new things breaking stuff and that's good enough for my needs.

> You can just pin the previous WinLibs tag instead (i.e. tag: 12.2.0-16.0.0-10.0.0-msvcrt-r5) although in this case it doesn't make any difference since all setup-winlibs-action@v1.11 changed was that default WinLibs tag.

Ah thanks for the tip. I was just following the instructions at https://github.com/bwoodsend/setup-winlibs-action#versioning, which implied we should do both and I didn't look any further into it.

**Comment by bwoodsend** [comment]
I think we can call this sufficiently historical to be closable...
