### ISSUE TITLE
Get latest release tag dynamically instead of hard code

### ISSUE THREAD

**Issue by SydneyOwl** [bwoodsend/setup-winlibs-action#4]
Hello!
@bwoodsend Thanks for your work! Using [setup-winlibs-action](https://github.com/bwoodsend/setup-winlibs-action) really speeds up my work process. 
However, would it be better if we get tag dynamically instead of hard-code as written in `install.py`  so that we can always get the latest version of winlibs? Just fetch json from `https://api.github.com/repos/brechtsanders/winlibs_mingw/releases/latest`, parse it, and get the latest tag by the key "tag_name".

**Comment by bwoodsend** [comment]
It would be nice to automate it but it's more complicated that just the most recent release. Some releases are pre-releases of gcc, others are older versions of gcc, and most significantly, some are linked against UCRT instead of MSVCRT meaning that anything they compile are only compatible with Windows 11 and later versions of Windows 10.

**Comment by bwoodsend** [comment]
I'm subscribed to winlib's releases so I get notifications when they occur. It rarely takes me more than 24 hours to get around to bumping the version and rerunning the tests.

**Comment by SydneyOwl** [comment]
Get it. Thanks for you reply!
